// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IZeroIDRegistry$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IZeroIDRegistry";
  readonly sourceName: "src/interfaces/IZeroIDRegistry.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"didHash","type":"bytes32"}],"name":"isActiveIdentity","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"controller","type":"address"}],"name":"resolveByController","outputs":[{"internalType":"bytes32","name":"didHash","type":"bytes32"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/interfaces/IZeroIDRegistry.sol";
  readonly buildInfoId: "solc-0_8_19-9d18e906cfb12f5f1bc2b6e9cc04d1890b52b5a7";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IZeroIDRegistry"]: IZeroIDRegistry$Type;
    ["src/interfaces/IZeroIDRegistry.sol:IZeroIDRegistry"]: IZeroIDRegistry$Type;
  }
}