FROM node:24.18.0-bookworm-slim AS dependencies
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

FROM dependencies AS build
ARG NEXT_PUBLIC_CHAIN_ENV
ARG NEXT_PUBLIC_AETHELRED_CHAIN_ID
ARG NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_BLOCK
ARG NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_HASH
ARG NEXT_PUBLIC_AETHELRED_RPC_URL
ARG NEXT_PUBLIC_AETHELRED_WS_URL
ARG NEXT_PUBLIC_AETHELRED_EXPLORER_URL
ARG NEXT_PUBLIC_NOBLEPAY_ADDRESS
ARG NEXT_PUBLIC_BUSINESS_REGISTRY_ADDRESS
ARG NEXT_PUBLIC_PAYMENT_CHANNELS_ADDRESS
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_WS_URL
ARG NEXT_PUBLIC_USDC_TOKEN_ADDRESS
ARG NEXT_PUBLIC_USDT_TOKEN_ADDRESS
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_APP_VERSION
# Optional. Only set for an acknowledged plaintext evaluation RPC; an
# https deployment leaves it empty and next.config.js keeps demanding https.
ARG NEXT_PUBLIC_ALLOW_INSECURE_TESTNET_RPC
ENV NEXT_PUBLIC_CHAIN_ENV=$NEXT_PUBLIC_CHAIN_ENV \
    NEXT_PUBLIC_AETHELRED_CHAIN_ID=$NEXT_PUBLIC_AETHELRED_CHAIN_ID \
    NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_BLOCK=$NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_BLOCK \
    NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_HASH=$NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_HASH \
    NEXT_PUBLIC_AETHELRED_RPC_URL=$NEXT_PUBLIC_AETHELRED_RPC_URL \
    NEXT_PUBLIC_AETHELRED_WS_URL=$NEXT_PUBLIC_AETHELRED_WS_URL \
    NEXT_PUBLIC_AETHELRED_EXPLORER_URL=$NEXT_PUBLIC_AETHELRED_EXPLORER_URL \
    NEXT_PUBLIC_NOBLEPAY_ADDRESS=$NEXT_PUBLIC_NOBLEPAY_ADDRESS \
    NEXT_PUBLIC_BUSINESS_REGISTRY_ADDRESS=$NEXT_PUBLIC_BUSINESS_REGISTRY_ADDRESS \
    NEXT_PUBLIC_PAYMENT_CHANNELS_ADDRESS=$NEXT_PUBLIC_PAYMENT_CHANNELS_ADDRESS \
    NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL \
    NEXT_PUBLIC_USDC_TOKEN_ADDRESS=$NEXT_PUBLIC_USDC_TOKEN_ADDRESS \
    NEXT_PUBLIC_USDT_TOKEN_ADDRESS=$NEXT_PUBLIC_USDT_TOKEN_ADDRESS \
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID \
    NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN \
    NEXT_PUBLIC_APP_VERSION=$NEXT_PUBLIC_APP_VERSION \
    NEXT_PUBLIC_ALLOW_INSECURE_TESTNET_RPC=$NEXT_PUBLIC_ALLOW_INSECURE_TESTNET_RPC
COPY next.config.js next-sitemap.config.js postcss.config.js tailwind.config.js tsconfig.json ./
COPY instrumentation-client.ts ./instrumentation-client.ts
COPY public ./public
COPY src ./src
RUN npm run build

FROM gcr.io/distroless/nodejs24-debian13@sha256:af85d11ce7ef10172855a6e3649e3e8125b1b9e3ca41849ec2918036f05cb212 AS runtime
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3008 \
    HOSTNAME=0.0.0.0
COPY --from=build --chown=65532:65532 /app/.next/standalone ./
COPY --from=build --chown=65532:65532 /app/.next/static ./.next/static
COPY --from=build --chown=65532:65532 /app/public ./public
USER 65532:65532
EXPOSE 3008
HEALTHCHECK --interval=20s --timeout=5s --start-period=30s --retries=5 \
  CMD ["/nodejs/bin/node", "-e", "fetch('http://127.0.0.1:3008/').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"]
CMD ["server.js"]
