FROM node:24.18.0-bookworm-slim AS dependencies
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps --ignore-scripts

FROM dependencies AS build
ARG NEXT_PUBLIC_CHAIN_ENV
ARG NEXT_PUBLIC_AETHELRED_CHAIN_ID
ARG NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_BLOCK
ARG NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_HASH
ARG NEXT_PUBLIC_AETHELRED_RPC_URL
ARG NEXT_PUBLIC_AETHELRED_WS_URL
ARG NEXT_PUBLIC_AETHELRED_EXPLORER_URL
ARG NEXT_PUBLIC_NOBLEPAY_ADDRESS
ARG NEXT_PUBLIC_BUSINESS_REGISTRY_ADDRESS
ARG NEXT_PUBLIC_PAYMENT_CHANNELS_ADDRESS
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_WS_URL
ARG NEXT_PUBLIC_USDC_TOKEN_ADDRESS
ARG NEXT_PUBLIC_USDT_TOKEN_ADDRESS
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_APP_VERSION
ENV NEXT_PUBLIC_CHAIN_ENV=$NEXT_PUBLIC_CHAIN_ENV \
    NEXT_PUBLIC_AETHELRED_CHAIN_ID=$NEXT_PUBLIC_AETHELRED_CHAIN_ID \
    NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_BLOCK=$NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_BLOCK \
    NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_HASH=$NEXT_PUBLIC_AETHELRED_NETWORK_ANCHOR_HASH \
    NEXT_PUBLIC_AETHELRED_RPC_URL=$NEXT_PUBLIC_AETHELRED_RPC_URL \
    NEXT_PUBLIC_AETHELRED_WS_URL=$NEXT_PUBLIC_AETHELRED_WS_URL \
    NEXT_PUBLIC_AETHELRED_EXPLORER_URL=$NEXT_PUBLIC_AETHELRED_EXPLORER_URL \
    NEXT_PUBLIC_NOBLEPAY_ADDRESS=$NEXT_PUBLIC_NOBLEPAY_ADDRESS \
    NEXT_PUBLIC_BUSINESS_REGISTRY_ADDRESS=$NEXT_PUBLIC_BUSINESS_REGISTRY_ADDRESS \
    NEXT_PUBLIC_PAYMENT_CHANNELS_ADDRESS=$NEXT_PUBLIC_PAYMENT_CHANNELS_ADDRESS \
    NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL \
    NEXT_PUBLIC_USDC_TOKEN_ADDRESS=$NEXT_PUBLIC_USDC_TOKEN_ADDRESS \
    NEXT_PUBLIC_USDT_TOKEN_ADDRESS=$NEXT_PUBLIC_USDT_TOKEN_ADDRESS \
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID \
    NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN \
    NEXT_PUBLIC_APP_VERSION=$NEXT_PUBLIC_APP_VERSION
COPY next.config.js next-sitemap.config.js postcss.config.js tailwind.config.js tsconfig.json ./
COPY instrumentation-client.ts ./instrumentation-client.ts
COPY public ./public
COPY src ./src
RUN npm run build

FROM node:24.18.0-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3008 \
    HOSTNAME=0.0.0.0
COPY --from=build --chown=node:node /app/.next/standalone ./
COPY --from=build --chown=node:node /app/.next/static ./.next/static
COPY --from=build --chown=node:node /app/public ./public
USER node
EXPOSE 3008
HEALTHCHECK --interval=20s --timeout=5s --start-period=30s --retries=5 \
  CMD ["node", "-e", "fetch('http://127.0.0.1:3008/').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"]
CMD ["node", "server.js"]
