// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockZeroIDRegistry$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockZeroIDRegistry";
  readonly sourceName: "src/MockZeroIDRegistry.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"didHash","type":"bytes32"}],"name":"isActiveIdentity","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"controller","type":"address"}],"name":"resolveByController","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"controller","type":"address"},{"internalType":"bytes32","name":"did","type":"bytes32"},{"internalType":"bool","name":"active","type":"bool"}],"name":"setIdentity","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x6080806040523461001657610157908161001c8239f35b600080fdfe60806040818152600436101561001457600080fd5b600091823560e01c908163274124d3146100cf57508063c8e1d7ff146100a25763d1cddc321461004357600080fd5b3461009e57606036600319011261009e5761005c610106565b906024356044359283151580940361009a5760018060a01b031684528360205280828520558352600160205282209060ff8019835416911617905580f35b8480fd5b5080fd5b503461009e57602036600319011261009e5760ff8160209360043581526001855220541690519015158152f35b91905034610102576020366003190112610102576020926001600160a01b036100f6610106565b16815280845220548152f35b8280fd5b600435906001600160a01b038216820361011c57565b600080fdfea2646970667358221220f9f7d03488ba733cf3724a8f8f1f0183d4b3646c8dd4f779116b1524b5db60ee64736f6c63430008130033";
  readonly deployedBytecode: "0x60806040818152600436101561001457600080fd5b600091823560e01c908163274124d3146100cf57508063c8e1d7ff146100a25763d1cddc321461004357600080fd5b3461009e57606036600319011261009e5761005c610106565b906024356044359283151580940361009a5760018060a01b031684528360205280828520558352600160205282209060ff8019835416911617905580f35b8480fd5b5080fd5b503461009e57602036600319011261009e5760ff8160209360043581526001855220541690519015158152f35b91905034610102576020366003190112610102576020926001600160a01b036100f6610106565b16815280845220548152f35b8280fd5b600435906001600160a01b038216820361011c57565b600080fdfea2646970667358221220f9f7d03488ba733cf3724a8f8f1f0183d4b3646c8dd4f779116b1524b5db60ee64736f6c63430008130033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/MockZeroIDRegistry.sol";
  readonly buildInfoId: "solc-0_8_19-9d18e906cfb12f5f1bc2b6e9cc04d1890b52b5a7";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockZeroIDRegistry"]: MockZeroIDRegistry$Type;
    ["src/MockZeroIDRegistry.sol:MockZeroIDRegistry"]: MockZeroIDRegistry$Type;
  }
}