/**
 * Contract ABIs for NoblePay protocol interactions.
 *
 * Minimal ABI definitions for the functions the frontend needs to call.
 * Full ABIs are generated by Foundry/Hardhat compilation.
 */

// ---------------------------------------------------------------------------
// NoblePay Core — Payment Router
// ---------------------------------------------------------------------------

export const NOBLEPAY_ABI = [
  // --- Read Functions ---
  {
    name: "getPayment",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "paymentId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "bytes32" },
          { name: "sender", type: "address" },
          { name: "recipient", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "token", type: "address" },
          { name: "status", type: "uint8" },
          { name: "complianceHash", type: "bytes32" },
          { name: "initiatedAt", type: "uint256" },
          { name: "settledAt", type: "uint256" },
          { name: "senderJurisdiction", type: "bytes2" },
          { name: "recipientJurisdiction", type: "bytes2" },
        ],
      },
    ],
  },
  {
    name: "getBusinessPayments",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "business", type: "address" },
      { name: "offset", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "id", type: "bytes32" },
          { name: "sender", type: "address" },
          { name: "recipient", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "token", type: "address" },
          { name: "status", type: "uint8" },
          { name: "complianceHash", type: "bytes32" },
          { name: "initiatedAt", type: "uint256" },
          { name: "settledAt", type: "uint256" },
          { name: "senderJurisdiction", type: "bytes2" },
          { name: "recipientJurisdiction", type: "bytes2" },
        ],
      },
    ],
  },

  // --- Write Functions ---
  {
    // Mirrors NoblePay.initiatePayment(address,uint256,address,bytes32,bytes3)
    // — payable, since native AETHEL payments escrow msg.value.
    name: "initiatePayment",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "_recipient", type: "address" },
      { name: "_amount", type: "uint256" },
      { name: "_token", type: "address" },
      { name: "_purposeHash", type: "bytes32" },
      { name: "_currencyCode", type: "bytes3" },
    ],
    outputs: [{ name: "paymentId", type: "bytes32" }],
  },
  {
    name: "submitComplianceResult",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "paymentId", type: "bytes32" },
      { name: "passed", type: "bool" },
      { name: "attestation", type: "bytes" },
    ],
    outputs: [],
  },
  {
    name: "settlePayment",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "paymentId", type: "bytes32" }],
    outputs: [],
  },

  // --- Events ---
  {
    name: "PaymentInitiated",
    type: "event",
    inputs: [
      { name: "paymentId", type: "bytes32", indexed: true },
      { name: "sender", type: "address", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "token", type: "address", indexed: false },
    ],
  },
  {
    name: "ComplianceResultSubmitted",
    type: "event",
    inputs: [
      { name: "paymentId", type: "bytes32", indexed: true },
      { name: "passed", type: "bool", indexed: false },
      { name: "attestation", type: "bytes", indexed: false },
    ],
  },
  {
    name: "PaymentSettled",
    type: "event",
    inputs: [
      { name: "paymentId", type: "bytes32", indexed: true },
      { name: "settledAt", type: "uint256", indexed: false },
    ],
  },
  {
    name: "PaymentRefunded",
    type: "event",
    inputs: [
      { name: "paymentId", type: "bytes32", indexed: true },
      { name: "reason", type: "bytes32", indexed: false },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// Compliance Oracle — TEE-backed screening engine
// ---------------------------------------------------------------------------

export const COMPLIANCE_ORACLE_ABI = [
  // --- Read Functions ---
  {
    name: "verifyAttestation",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "attestation", type: "bytes" },
      { name: "paymentId", type: "bytes32" },
    ],
    outputs: [
      { name: "valid", type: "bool" },
      { name: "teeNodeId", type: "bytes32" },
    ],
  },
  {
    name: "getRiskThresholds",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "lowThreshold", type: "uint256" },
      { name: "mediumThreshold", type: "uint256" },
      { name: "highThreshold", type: "uint256" },
      { name: "criticalThreshold", type: "uint256" },
    ],
  },
  {
    name: "getTEENodeStatus",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "nodeId", type: "bytes32" }],
    outputs: [
      { name: "active", type: "bool" },
      { name: "lastAttestation", type: "uint256" },
      { name: "processedCount", type: "uint256" },
      { name: "uptime", type: "uint256" },
    ],
  },

  // --- Events ---
  {
    name: "AttestationVerified",
    type: "event",
    inputs: [
      { name: "paymentId", type: "bytes32", indexed: true },
      { name: "teeNodeId", type: "bytes32", indexed: true },
      { name: "valid", type: "bool", indexed: false },
    ],
  },
  {
    name: "RiskThresholdsUpdated",
    type: "event",
    inputs: [
      { name: "lowThreshold", type: "uint256", indexed: false },
      { name: "mediumThreshold", type: "uint256", indexed: false },
      { name: "highThreshold", type: "uint256", indexed: false },
      { name: "criticalThreshold", type: "uint256", indexed: false },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// Business Registry — KYC and identity management
// ---------------------------------------------------------------------------

export const BUSINESS_REGISTRY_ABI = [
  // --- Read Functions ---
  {
    name: "getBusinessDetails",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "business", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "name", type: "string" },
          { name: "jurisdiction", type: "bytes2" },
          { name: "tier", type: "uint8" },
          { name: "kycStatus", type: "uint8" },
          { name: "registeredAt", type: "uint256" },
          { name: "dailyLimit", type: "uint256" },
          { name: "monthlyLimit", type: "uint256" },
          { name: "dailyUsed", type: "uint256" },
          { name: "monthlyUsed", type: "uint256" },
        ],
      },
    ],
  },
  {
    // Public mapping getter — the deployed BusinessRegistry has no
    // isBusinessRegistered(); registration state is businesses(addr)
    // .registeredAt != 0.
    name: "businesses",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "wallet", type: "address" },
      { name: "licenseNumber", type: "string" },
      { name: "businessName", type: "string" },
      { name: "jurisdiction", type: "uint8" },
      { name: "kycStatus", type: "uint8" },
      { name: "tier", type: "uint8" },
      { name: "registeredAt", type: "uint256" },
      { name: "lastVerified", type: "uint256" },
      { name: "complianceOfficer", type: "address" },
    ],
  },
  {
    name: "getBusinessTier",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "business", type: "address" }],
    outputs: [{ name: "", type: "uint8" }],
  },

  // --- Write Functions ---
  {
    // Mirrors BusinessRegistry.registerBusiness(string,string,Jurisdiction,
    // address) — the previous (string,bytes2,bytes32) shape predated the
    // deployed contract and mis-encoded every registration.
    name: "registerBusiness",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_licenseNumber", type: "string" },
      { name: "_businessName", type: "string" },
      { name: "_jurisdiction", type: "uint8" },
      { name: "_complianceOfficer", type: "address" },
    ],
    outputs: [],
  },

  // --- Events ---
  {
    name: "BusinessRegistered",
    type: "event",
    inputs: [
      { name: "business", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "jurisdiction", type: "bytes2", indexed: true },
      { name: "tier", type: "uint8", indexed: false },
    ],
  },
  {
    name: "TierUpgraded",
    type: "event",
    inputs: [
      { name: "business", type: "address", indexed: true },
      { name: "oldTier", type: "uint8", indexed: false },
      { name: "newTier", type: "uint8", indexed: false },
    ],
  },
  {
    name: "KYCStatusUpdated",
    type: "event",
    inputs: [
      { name: "business", type: "address", indexed: true },
      { name: "newStatus", type: "uint8", indexed: false },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// Travel Rule — FATF-compliant originator/beneficiary data
// ---------------------------------------------------------------------------

export const TRAVEL_RULE_ABI = [
  // --- Read Functions ---
  {
    name: "getTravelRuleStatus",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "paymentId", type: "bytes32" }],
    outputs: [
      { name: "submitted", type: "bool" },
      { name: "verified", type: "bool" },
      { name: "dataHash", type: "bytes32" },
      { name: "submittedAt", type: "uint256" },
    ],
  },

  // --- Write Functions ---
  {
    name: "submitTravelRuleData",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "paymentId", type: "bytes32" },
      { name: "encryptedOriginatorData", type: "bytes" },
      { name: "encryptedBeneficiaryData", type: "bytes" },
    ],
    outputs: [],
  },

  // --- Events ---
  {
    name: "TravelRuleDataSubmitted",
    type: "event",
    inputs: [
      { name: "paymentId", type: "bytes32", indexed: true },
      { name: "dataHash", type: "bytes32", indexed: false },
      { name: "submittedAt", type: "uint256", indexed: false },
    ],
  },
  {
    name: "TravelRuleVerified",
    type: "event",
    inputs: [
      { name: "paymentId", type: "bytes32", indexed: true },
      { name: "verifiedBy", type: "address", indexed: true },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// ERC-20 (approve/allowance surface used by the liquidity flows)
// ---------------------------------------------------------------------------

export const ERC20_ABI = [
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "allowance",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "decimals",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    name: "symbol",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
] as const;

// ---------------------------------------------------------------------------
// LiquidityPool — mirrors contracts/src/LiquidityPool.sol
// ---------------------------------------------------------------------------

export const LIQUIDITY_POOL_ABI = [
  // --- Views ---
  {
    name: "getPool",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "_poolId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "token0", type: "address" },
          { name: "token1", type: "address" },
          { name: "reserveToken0", type: "uint256" },
          { name: "reserveToken1", type: "uint256" },
          { name: "totalLiquidity", type: "uint256" },
          { name: "feeRateBP", type: "uint256" },
          { name: "flashFeeRateBP", type: "uint256" },
          { name: "currentTick", type: "int24" },
          { name: "createdAt", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
  },
  {
    name: "getPosition",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "_positionId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "provider", type: "address" },
          { name: "amountToken0", type: "uint256" },
          { name: "amountToken1", type: "uint256" },
          { name: "tickLower", type: "int24" },
          { name: "tickUpper", type: "int24" },
          { name: "feesEarnedToken0", type: "uint256" },
          { name: "feesEarnedToken1", type: "uint256" },
          { name: "createdAt", type: "uint256" },
          { name: "lastUpdatedAt", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
    ],
  },
  {
    name: "getPoolTVL",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "_poolId", type: "bytes32" }],
    outputs: [
      { name: "token0", type: "uint256" },
      { name: "token1", type: "uint256" },
    ],
  },
  {
    name: "getPoolUtilization",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "_poolId", type: "bytes32" }],
    outputs: [{ name: "ratioBP", type: "uint256" }],
  },
  {
    name: "getPoolHealth",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "_poolId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  // --- Writes ---
  {
    name: "addLiquidity",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_poolId", type: "bytes32" },
      { name: "_amountToken0", type: "uint256" },
      { name: "_amountToken1", type: "uint256" },
      { name: "_tickLower", type: "int24" },
      { name: "_tickUpper", type: "int24" },
    ],
    outputs: [{ name: "positionId", type: "bytes32" }],
  },
  {
    name: "removeLiquidity",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_poolId", type: "bytes32" },
      { name: "_positionId", type: "bytes32" },
    ],
    outputs: [],
  },
  // --- Events ---
  {
    name: "PoolCreated",
    type: "event",
    inputs: [
      { name: "poolId", type: "bytes32", indexed: true },
      { name: "token0", type: "address", indexed: true },
      { name: "token1", type: "address", indexed: true },
      { name: "feeRateBP", type: "uint256", indexed: false },
    ],
  },
  {
    name: "LiquidityAdded",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "poolId", type: "bytes32", indexed: true },
      { name: "provider", type: "address", indexed: true },
      { name: "amountToken0", type: "uint256", indexed: false },
      { name: "amountToken1", type: "uint256", indexed: false },
      { name: "tickLower", type: "int24", indexed: false },
      { name: "tickUpper", type: "int24", indexed: false },
    ],
  },
  {
    name: "LiquidityRemoved",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "poolId", type: "bytes32", indexed: true },
      { name: "provider", type: "address", indexed: true },
      { name: "amountToken0", type: "uint256", indexed: false },
      { name: "amountToken1", type: "uint256", indexed: false },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// MultiSigTreasury — generated from
// contracts/artifacts/src/MultiSigTreasury.sol/MultiSigTreasury.json.
//
// Generated rather than hand-written on purpose: a hand-maintained tuple that
// drifts from the deployed struct decodes silently wrong (see the TerraQura
// getMetadata incident). Regenerate with scripts/gen-multisig-abi.mjs after any
// contract change.
//
// Approval tiers are amount-based and 6-decimal denominated (USDC/USDT):
//   <= SMALL_TX_THRESHOLD (10,000)   -> smallThreshold approvals
//   <= LARGE_TX_THRESHOLD (100,000)  -> mediumThreshold approvals
//    > LARGE_TX_THRESHOLD            -> largeThreshold approvals + 48h timelock
// ---------------------------------------------------------------------------

export const MULTISIG_TREASURY_ABI = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "proposalId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "approvalCount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "required",
        "type": "uint256"
      }
    ],
    "name": "ProposalApproved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "proposalId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "proposer",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "enum MultiSigTreasury.TxTier",
        "name": "tier",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "isEmergency",
        "type": "bool"
      }
    ],
    "name": "ProposalCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "proposalId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "executor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "executedAt",
        "type": "uint256"
      }
    ],
    "name": "ProposalExecuted",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "ADMIN_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "LARGE_TX_THRESHOLD",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "SIGNER_ROLE",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "SMALL_TX_THRESHOLD",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_proposalId",
        "type": "bytes32"
      }
    ],
    "name": "approveProposal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_proposalId",
        "type": "bytes32"
      }
    ],
    "name": "cancelProposal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_recipient",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_amount",
        "type": "uint256"
      },
      {
        "internalType": "enum MultiSigTreasury.SpendingCategory",
        "name": "_category",
        "type": "uint8"
      },
      {
        "internalType": "string",
        "name": "_description",
        "type": "string"
      },
      {
        "internalType": "bool",
        "name": "_isEmergency",
        "type": "bool"
      },
      {
        "internalType": "bytes32",
        "name": "_budgetId",
        "type": "bytes32"
      }
    ],
    "name": "createProposal",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "proposalId",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_proposalId",
        "type": "bytes32"
      }
    ],
    "name": "executeProposal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_proposalId",
        "type": "bytes32"
      }
    ],
    "name": "getProposal",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "proposalId",
            "type": "bytes32"
          },
          {
            "internalType": "address",
            "name": "proposer",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "recipient",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "token",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
          },
          {
            "internalType": "enum MultiSigTreasury.SpendingCategory",
            "name": "category",
            "type": "uint8"
          },
          {
            "internalType": "string",
            "name": "description",
            "type": "string"
          },
          {
            "internalType": "enum MultiSigTreasury.TxTier",
            "name": "tier",
            "type": "uint8"
          },
          {
            "internalType": "enum MultiSigTreasury.ProposalStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "approvalCount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "rejectionCount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "requiredApprovals",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "createdAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "timelockExpiry",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "expiresAt",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isEmergency",
            "type": "bool"
          },
          {
            "internalType": "bytes32",
            "name": "budgetId",
            "type": "bytes32"
          }
        ],
        "internalType": "struct MultiSigTreasury.Proposal",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "hasRole",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_proposalId",
        "type": "bytes32"
      }
    ],
    "name": "rejectProposal",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "signerConfig",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "totalSigners",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "smallThreshold",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "mediumThreshold",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "largeThreshold",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "emergencyThreshold",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "signers",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
