/**
 * Contract ABIs for NoblePay protocol interactions.
 *
 * Minimal ABI definitions for the functions the frontend needs to call.
 * Full ABIs are generated by Foundry/Hardhat compilation.
 */

// ---------------------------------------------------------------------------
// NoblePay Core — Payment Router
// ---------------------------------------------------------------------------

export const NOBLEPAY_ABI = [
  // --- Read Functions ---
  {
    name: 'getPayment',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'paymentId', type: 'bytes32' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'id', type: 'bytes32' },
          { name: 'sender', type: 'address' },
          { name: 'recipient', type: 'address' },
          { name: 'amount', type: 'uint256' },
          { name: 'token', type: 'address' },
          { name: 'status', type: 'uint8' },
          { name: 'complianceHash', type: 'bytes32' },
          { name: 'initiatedAt', type: 'uint256' },
          { name: 'settledAt', type: 'uint256' },
          { name: 'senderJurisdiction', type: 'bytes2' },
          { name: 'recipientJurisdiction', type: 'bytes2' },
        ],
      },
    ],
  },
  {
    name: 'getBusinessPayments',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'business', type: 'address' },
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        components: [
          { name: 'id', type: 'bytes32' },
          { name: 'sender', type: 'address' },
          { name: 'recipient', type: 'address' },
          { name: 'amount', type: 'uint256' },
          { name: 'token', type: 'address' },
          { name: 'status', type: 'uint8' },
          { name: 'complianceHash', type: 'bytes32' },
          { name: 'initiatedAt', type: 'uint256' },
          { name: 'settledAt', type: 'uint256' },
          { name: 'senderJurisdiction', type: 'bytes2' },
          { name: 'recipientJurisdiction', type: 'bytes2' },
        ],
      },
    ],
  },

  // --- Write Functions ---
  {
    name: 'initiatePayment',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'recipient', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'token', type: 'address' },
      { name: 'recipientJurisdiction', type: 'bytes2' },
      { name: 'memo', type: 'bytes' },
    ],
    outputs: [{ name: 'paymentId', type: 'bytes32' }],
  },
  {
    name: 'submitComplianceResult',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'paymentId', type: 'bytes32' },
      { name: 'passed', type: 'bool' },
      { name: 'attestation', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    name: 'settlePayment',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'paymentId', type: 'bytes32' }],
    outputs: [],
  },

  // --- Events ---
  {
    name: 'PaymentInitiated',
    type: 'event',
    inputs: [
      { name: 'paymentId', type: 'bytes32', indexed: true },
      { name: 'sender', type: 'address', indexed: true },
      { name: 'recipient', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'token', type: 'address', indexed: false },
    ],
  },
  {
    name: 'ComplianceResultSubmitted',
    type: 'event',
    inputs: [
      { name: 'paymentId', type: 'bytes32', indexed: true },
      { name: 'passed', type: 'bool', indexed: false },
      { name: 'attestation', type: 'bytes', indexed: false },
    ],
  },
  {
    name: 'PaymentSettled',
    type: 'event',
    inputs: [
      { name: 'paymentId', type: 'bytes32', indexed: true },
      { name: 'settledAt', type: 'uint256', indexed: false },
    ],
  },
  {
    name: 'PaymentRefunded',
    type: 'event',
    inputs: [
      { name: 'paymentId', type: 'bytes32', indexed: true },
      { name: 'reason', type: 'bytes32', indexed: false },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// Compliance Oracle — TEE-backed screening engine
// ---------------------------------------------------------------------------

export const COMPLIANCE_ORACLE_ABI = [
  // --- Read Functions ---
  {
    name: 'verifyAttestation',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'attestation', type: 'bytes' },
      { name: 'paymentId', type: 'bytes32' },
    ],
    outputs: [
      { name: 'valid', type: 'bool' },
      { name: 'teeNodeId', type: 'bytes32' },
    ],
  },
  {
    name: 'getRiskThresholds',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'lowThreshold', type: 'uint256' },
      { name: 'mediumThreshold', type: 'uint256' },
      { name: 'highThreshold', type: 'uint256' },
      { name: 'criticalThreshold', type: 'uint256' },
    ],
  },
  {
    name: 'getTEENodeStatus',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'nodeId', type: 'bytes32' }],
    outputs: [
      { name: 'active', type: 'bool' },
      { name: 'lastAttestation', type: 'uint256' },
      { name: 'processedCount', type: 'uint256' },
      { name: 'uptime', type: 'uint256' },
    ],
  },

  // --- Events ---
  {
    name: 'AttestationVerified',
    type: 'event',
    inputs: [
      { name: 'paymentId', type: 'bytes32', indexed: true },
      { name: 'teeNodeId', type: 'bytes32', indexed: true },
      { name: 'valid', type: 'bool', indexed: false },
    ],
  },
  {
    name: 'RiskThresholdsUpdated',
    type: 'event',
    inputs: [
      { name: 'lowThreshold', type: 'uint256', indexed: false },
      { name: 'mediumThreshold', type: 'uint256', indexed: false },
      { name: 'highThreshold', type: 'uint256', indexed: false },
      { name: 'criticalThreshold', type: 'uint256', indexed: false },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// Business Registry — KYC and identity management
// ---------------------------------------------------------------------------

export const BUSINESS_REGISTRY_ABI = [
  // --- Read Functions ---
  {
    name: 'getBusinessDetails',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'business', type: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'owner', type: 'address' },
          { name: 'name', type: 'string' },
          { name: 'jurisdiction', type: 'bytes2' },
          { name: 'tier', type: 'uint8' },
          { name: 'kycStatus', type: 'uint8' },
          { name: 'registeredAt', type: 'uint256' },
          { name: 'dailyLimit', type: 'uint256' },
          { name: 'monthlyLimit', type: 'uint256' },
          { name: 'dailyUsed', type: 'uint256' },
          { name: 'monthlyUsed', type: 'uint256' },
        ],
      },
    ],
  },
  {
    name: 'isBusinessRegistered',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'business', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'getBusinessTier',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'business', type: 'address' }],
    outputs: [{ name: '', type: 'uint8' }],
  },

  // --- Write Functions ---
  {
    name: 'registerBusiness',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'jurisdiction', type: 'bytes2' },
      { name: 'kycDocumentHash', type: 'bytes32' },
    ],
    outputs: [],
  },

  // --- Events ---
  {
    name: 'BusinessRegistered',
    type: 'event',
    inputs: [
      { name: 'business', type: 'address', indexed: true },
      { name: 'name', type: 'string', indexed: false },
      { name: 'jurisdiction', type: 'bytes2', indexed: true },
      { name: 'tier', type: 'uint8', indexed: false },
    ],
  },
  {
    name: 'TierUpgraded',
    type: 'event',
    inputs: [
      { name: 'business', type: 'address', indexed: true },
      { name: 'oldTier', type: 'uint8', indexed: false },
      { name: 'newTier', type: 'uint8', indexed: false },
    ],
  },
  {
    name: 'KYCStatusUpdated',
    type: 'event',
    inputs: [
      { name: 'business', type: 'address', indexed: true },
      { name: 'newStatus', type: 'uint8', indexed: false },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// Travel Rule — FATF-compliant originator/beneficiary data
// ---------------------------------------------------------------------------

export const TRAVEL_RULE_ABI = [
  // --- Read Functions ---
  {
    name: 'getTravelRuleStatus',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'paymentId', type: 'bytes32' }],
    outputs: [
      { name: 'submitted', type: 'bool' },
      { name: 'verified', type: 'bool' },
      { name: 'dataHash', type: 'bytes32' },
      { name: 'submittedAt', type: 'uint256' },
    ],
  },

  // --- Write Functions ---
  {
    name: 'submitTravelRuleData',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'paymentId', type: 'bytes32' },
      { name: 'encryptedOriginatorData', type: 'bytes' },
      { name: 'encryptedBeneficiaryData', type: 'bytes' },
    ],
    outputs: [],
  },

  // --- Events ---
  {
    name: 'TravelRuleDataSubmitted',
    type: 'event',
    inputs: [
      { name: 'paymentId', type: 'bytes32', indexed: true },
      { name: 'dataHash', type: 'bytes32', indexed: false },
      { name: 'submittedAt', type: 'uint256', indexed: false },
    ],
  },
  {
    name: 'TravelRuleVerified',
    type: 'event',
    inputs: [
      { name: 'paymentId', type: 'bytes32', indexed: true },
      { name: 'verifiedBy', type: 'address', indexed: true },
    ],
  },
] as const;
