// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface INoblePayAttack$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "INoblePayAttack";
  readonly sourceName: "src/NoblePayAttackMocks.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"paymentId","type":"bytes32"}],"name":"cancelPayment","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"paymentId","type":"bytes32"}],"name":"refundPayment","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"paymentId","type":"bytes32"}],"name":"settlePayment","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/NoblePayAttackMocks.sol";
  readonly buildInfoId: "solc-0_8_19-9d18e906cfb12f5f1bc2b6e9cc04d1890b52b5a7";
};

export interface INoblePaySettle$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "INoblePaySettle";
  readonly sourceName: "src/NoblePayAttackMocks.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"paymentId","type":"bytes32"}],"name":"settlePayment","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/NoblePayAttackMocks.sol";
  readonly buildInfoId: "solc-0_8_19-9d18e906cfb12f5f1bc2b6e9cc04d1890b52b5a7";
};

export interface MaliciousNativeReceiver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MaliciousNativeReceiver";
  readonly sourceName: "src/NoblePayAttackMocks.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"_noblepay","type":"address"},{"internalType":"bytes32","name":"_reentryTarget","type":"bytes32"},{"internalType":"uint8","name":"_mode","type":"uint8"}],"name":"arm","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"armed","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"mode","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"noblepay","outputs":[{"internalType":"contract INoblePayAttack","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"reentryTarget","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"stateMutability":"payable","type":"receive"}];
  readonly bytecode: "0x60808060405234610016576102cc908161001c8239f35b600080fdfe60806040908082526004361015610134575b50361561001d57600080fd5b60025460ff8160081c1661002d57005b61ff0019811660025560ff168061009f57506000805460015491929183916001600160a01b0316803b1561009b57602483928551968793849263192fed4560e11b845260048401525af191821561009157505061008657005b61008f9061026c565b005b51903d90823e3d90fd5b8280fd5b6001036100ed576000805460015491929183916001600160a01b0316803b1561009b57602483928551968793849263de8f8b3f60e01b845260048401525af191821561009157505061008657005b6000805460015491929183916001600160a01b0316803b1561009b57602483928551968793849263188dd2cf60e31b845260048401525af191821561009157505061008657005b600090813560e01c908163295a52121461024d575080632c790aa9146101e55780632f411093146101be5780638ce4e8a8146101965763eb9d77f9036100115790346101925781600319360112610192576020906001549051908152f35b5080fd5b509034610192578160031936011261019257905490516001600160a01b039091168152602090f35b50903461019257816003193601126101925760209060ff60025460081c1690519015158152f35b503461024a57606036600319011261024a576004356001600160a01b038116908190036101925760443560ff811680910361009b57610100916bffffffffffffffffffffffff60a01b84541617835560243560015561ffff1960025416171760025580f35b80fd5b90503461019257816003193601126101925760209060ff600254168152f35b67ffffffffffffffff811161028057604052565b634e487b7160e01b600052604160045260246000fdfea264697066735822122051d76ae78a481825b95e3ca40cd7083c06644eccbdc5bdc832a6de053f76af9864736f6c63430008130033";
  readonly deployedBytecode: "0x60806040908082526004361015610134575b50361561001d57600080fd5b60025460ff8160081c1661002d57005b61ff0019811660025560ff168061009f57506000805460015491929183916001600160a01b0316803b1561009b57602483928551968793849263192fed4560e11b845260048401525af191821561009157505061008657005b61008f9061026c565b005b51903d90823e3d90fd5b8280fd5b6001036100ed576000805460015491929183916001600160a01b0316803b1561009b57602483928551968793849263de8f8b3f60e01b845260048401525af191821561009157505061008657005b6000805460015491929183916001600160a01b0316803b1561009b57602483928551968793849263188dd2cf60e31b845260048401525af191821561009157505061008657005b600090813560e01c908163295a52121461024d575080632c790aa9146101e55780632f411093146101be5780638ce4e8a8146101965763eb9d77f9036100115790346101925781600319360112610192576020906001549051908152f35b5080fd5b509034610192578160031936011261019257905490516001600160a01b039091168152602090f35b50903461019257816003193601126101925760209060ff60025460081c1690519015158152f35b503461024a57606036600319011261024a576004356001600160a01b038116908190036101925760443560ff811680910361009b57610100916bffffffffffffffffffffffff60a01b84541617835560243560015561ffff1960025416171760025580f35b80fd5b90503461019257816003193601126101925760209060ff600254168152f35b67ffffffffffffffff811161028057604052565b634e487b7160e01b600052604160045260246000fdfea264697066735822122051d76ae78a481825b95e3ca40cd7083c06644eccbdc5bdc832a6de053f76af9864736f6c63430008130033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/NoblePayAttackMocks.sol";
  readonly buildInfoId: "solc-0_8_19-9d18e906cfb12f5f1bc2b6e9cc04d1890b52b5a7";
};

export interface ReentrantSealGate$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ReentrantSealGate";
  readonly sourceName: "src/NoblePayAttackMocks.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"_noblepay","type":"address"},{"internalType":"bytes32","name":"_reentryTarget","type":"bytes32"}],"name":"arm","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"},{"internalType":"address","name":"","type":"address"}],"name":"isCleared","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"noblepay","outputs":[{"internalType":"contract INoblePaySettle","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"reentryTarget","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"},{"internalType":"address","name":"","type":"address"}],"name":"requireCleared","outputs":[],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080806040523461001657610212908161001c8239f35b600080fdfe60806040818152600436101561001457600080fd5b600091823560e01c9081637b820747146101855781638ce4e8a8146101615750806391496c86146100b7578063e55df4741461007a5763eb9d77f91461005957600080fd5b346100765781600319360112610076576020906001549051908152f35b5080fd5b5034610076573660031901126100b4576001600160a01b0361009a6101ab565b82546001600160a01b031916911617815560243560015580f35b80fd5b50346100765780600319360112610076576100d06101ab565b506100d96101c6565b50815460015483916001600160a01b0316803b1561015d57602483928551948593849263192fed4560e11b845260048401525af1801561015157610122575b6020825160018152f35b67ffffffffffffffff811161013d5760209250815238610118565b634e487b7160e01b83526041600452602483fd5b505051903d90823e3d90fd5b8280fd5b83903461007657816003193601126100765790546001600160a01b03168152602090f35b505034610076573660031901126100b45761019e6101ab565b506101a76101c6565b5080f35b600435906001600160a01b03821682036101c157565b600080fd5b602435906001600160a01b03821682036101c15756fea2646970667358221220d6a37693136c5a9fd541b3d3d7fe6b8435ae155cb5316795a006f7c08451fb4f64736f6c63430008130033";
  readonly deployedBytecode: "0x60806040818152600436101561001457600080fd5b600091823560e01c9081637b820747146101855781638ce4e8a8146101615750806391496c86146100b7578063e55df4741461007a5763eb9d77f91461005957600080fd5b346100765781600319360112610076576020906001549051908152f35b5080fd5b5034610076573660031901126100b4576001600160a01b0361009a6101ab565b82546001600160a01b031916911617815560243560015580f35b80fd5b50346100765780600319360112610076576100d06101ab565b506100d96101c6565b50815460015483916001600160a01b0316803b1561015d57602483928551948593849263192fed4560e11b845260048401525af1801561015157610122575b6020825160018152f35b67ffffffffffffffff811161013d5760209250815238610118565b634e487b7160e01b83526041600452602483fd5b505051903d90823e3d90fd5b8280fd5b83903461007657816003193601126100765790546001600160a01b03168152602090f35b505034610076573660031901126100b45761019e6101ab565b506101a76101c6565b5080f35b600435906001600160a01b03821682036101c157565b600080fd5b602435906001600160a01b03821682036101c15756fea2646970667358221220d6a37693136c5a9fd541b3d3d7fe6b8435ae155cb5316795a006f7c08451fb4f64736f6c63430008130033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/NoblePayAttackMocks.sol";
  readonly buildInfoId: "solc-0_8_19-9d18e906cfb12f5f1bc2b6e9cc04d1890b52b5a7";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["INoblePayAttack"]: INoblePayAttack$Type
    ["INoblePaySettle"]: INoblePaySettle$Type
    ["MaliciousNativeReceiver"]: MaliciousNativeReceiver$Type
    ["ReentrantSealGate"]: ReentrantSealGate$Type;
    ["src/NoblePayAttackMocks.sol:INoblePayAttack"]: INoblePayAttack$Type
    ["src/NoblePayAttackMocks.sol:INoblePaySettle"]: INoblePaySettle$Type
    ["src/NoblePayAttackMocks.sol:MaliciousNativeReceiver"]: MaliciousNativeReceiver$Type
    ["src/NoblePayAttackMocks.sol:ReentrantSealGate"]: ReentrantSealGate$Type;
  }
}